version: 2.1

orbs:
  android: circleci/android@2.5.0

jobs:
  build-apk:
    executor:
      name: android/android-machine
      resource-class: medium
    steps:
      - checkout

      - run:
          name: Install Flutter
          command: |
            curl -sSLO https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.44.1-stable.tar.xz
            tar xf flutter_linux_3.44.1-stable.tar.xz -C /home/circleci/
            rm flutter_linux_3.44.1-stable.tar.xz
            echo 'export PATH="$PATH:/home/circleci/flutter/bin:/home/circleci/flutter/bin/cache/dart-sdk/bin"' >> $BASH_ENV
            flutter config --no-analytics

      - run:
          name: Install dependencies
          command: flutter pub get

      - run:
          name: Generate Drift code
          command: dart run build_runner build --delete-conflicting-outputs

      - run:
          name: Build debug APK
          command: flutter build apk --debug --target-platform android-arm64

      - store_artifacts:
          path: build/app/outputs/flutter-apk/
          destination: handa-apk

workflows:
  version: 2
  build:
    jobs:
      - build-apk:
          filters:
            branches:
              only: main
