version: 2.1

orbs:
  flutter: circleci/flutter@2.1.0

jobs:
  build-apk:
    docker:
      - image: cimg/android:2024.12.1
    resource_class: medium
    steps:
      - checkout
      - flutter/install_sdk_and_pub:
          version: "3.29.2"
      - run: dart run build_runner build --delete-conflicting-outputs
      - run: flutter build apk --debug --target-platform android-arm64
      - store_artifacts:
          path: build/app/outputs/flutter-apk/
          destination: handa-apk

workflows:
  build:
    jobs:
      - build-apk:
          filters:
            branches:
              only: main
